//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnkaraPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMessage
    {
        public int MessageID { get; set; }
        public string SenderMessage { get; set; }
        public string ReceiverMessage { get; set; }
        public string Subject { get; set; }
        public string MessageBody { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
    }
}
